---
- name: First 5 minutes in new servers
  hosts: webservers
  become: yes
  become_user: root
  vars_files:
    - vars.yml

  tasks:
    - name: Update APT packages cache
      apt: update_cache=yes

    - name: Perform aptitude safe-upgrade
      apt:
          upgrade: dist

    - name: Create new user
      user: name={{ server_user_name }} password={{ server_user_password }} shell=/bin/bash

    - name: Add user to sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '{{ server_user_name }} ALL'
        line: '{{ server_user_name }} ALL=(ALL) ALL'
        state: present

    - name: Add authorized_keys for the user
      authorized_key: user={{ server_user_name }} key="{{ lookup('file', item) }}"
      with_fileglob:
        '{{ user_public_keys }}'

    - name: Disallow root SSH access
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify: Restart ssh

    - name: Disallow password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart ssh

    - name: Install required packages
      apt: state=installed pkg={{ item }}
      with_items:
      - '{{ required_packages }}'

    # Allow only ssh and http(s) ports
    - name: Allow ssh and http(s) connections
      ufw:
        rule: allow
        port: '{{ item }}'
      with_items:
        - '{{ ufw_allowed_ports }}'

    # Flynn ports
    - name: Allow port range for flynn tcp
      ufw:
        rule: allow
        proto: tcp
        port: '{{ flynn_tcp_port_range }}'

    - name: UFW allow Flynn interfaces
      ufw:
        rule: allow
        interface: '{{ item }}'
        direction: in
      with_items: '{{ flynn_interfaces }}'

    # Needed for docker/flynn
    - name: Set ufw default forward policy to ACCEPT
      lineinfile:
        path: /etc/default/ufw
        regexp: '^DEFAULT_FORWARD_POLICY='
        line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
        state: present

    - name: Enable ufw/firewall
      ufw: state=enabled policy=deny

    - name: Set up Postfix to relay mail
      debconf: name=postfix
               question='{{ item.question }}'
               value='{{ item.value }}'
               vtype='{{ item.vtype }}'
      with_items:
        - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
        - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }

    - name: Email logwatch summary daily
      lineinfile:
        path: /etc/cron.daily/00logwatch
        regexp: '^/usr/sbin/logwatch'
        line: '/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high'
        state: present
        create: yes

    - name: Adjust unattended-upgrades to just install security updates
      copy: src=templates/50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades

    - name: Adjust APT update intervals
      copy: src=templates/10periodic dest=/etc/apt/apt.conf.d/10periodic

    - name: set timezone
      timezone:
        name: '{{ timezone }}'

    - name: restart server
      shell: sleep 2 && /sbin/shutdown -r now "Restarting from Ansible"
      async: 1
      poll: 0

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted

    - name: Reload ufw
      command: ufw reload
